apiVersion: v1
kind: Secret
metadata:
  name: laravel-env-secret
type: Opaque
stringData:
  # Buradaki değerler base64 gerektirmez, 'stringData' otomatik çevirir.
  APP_KEY: "base64:Yhzy6RvRgIt2bnvHf+YTHQ4CoJJVljeo6GmHVzmoADE=" # Laravel app:generate ile oluşan key
  DB_CONNECTION: "sqlite"
#  DB_HOST: "mysql-service"
#  DB_DATABASE: "laravel_db"
#  DB_USERNAME: "laravel_user"
#  DB_PASSWORD: "gizli_sifre_123"
  APP_DEBUG: "true"
